language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
addons:
  apt_packages:
    - pandoc
before_install:
  - cp .env.mock .env
  - npm install npm@latest -g
install:
  - pip install tox-travis
  - pip install bumpversion
  - pip install -r requirements.txt
  - npm install @semantic-release/exec
script:
  - pip install -U python-dotenv
  - tox
deploy:
  matrix:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
  - provider: pypi
    user: mamoonraja
    password:
      secure: DHB0BKMLg0HwDypKem4QxaiftNaZ/949lsfQXvPyGKRm0FkyD+yymdSRbxdm1wJVOSTl36zknqQVVBlG+PFjOWEjDyBSftaL4m9l8psgDOfb9FRpyyG9TMatFQRTDu8wYt/ex4yk3x/kmXoFpcP8z4Ra+2VijUpas5vLieJwhdTVs+sSwts69eYWlC8+JrS1mSr3woAg+U24xYvbTAsr7WtGmlZ6Wt0yObEqTjyn61Lnf1J3hEmjgBL74fMlqK0oaRwCeVEB0Yz/XiMjIJi2q8Zkzg3HIPPBCr/PEa6RYu2qd3jSNt6i80RdLEUHTcetYgPGw9LC+42KDzW/SgCToarQQO0Fp4konFaEwpeWvF3uYPNbIZyzPsfDgGJtqbIIUWuZUxrFbQ2p2YmIxUpdA42pvvqL+K/FzW8trM1qfb02h+kGC113WlmtUvqtTs2B8a/DFOmuiVw3VVBTiUoxmmUoGgpWSbL7rzf7wy7scKnS6ewm5NTC1FRSERR/W9SnUY61AFFs0tlEB/UCN7pWKIoxK2pp9n8H5qDDRdg0vzxzGdvdnCh9iEoKEfbUkQas5fkzz5StOo2I0o5BnYmPJOnfd4IugH+7pVvCHD+6UyLiO1I/v3slCcMdb3JagGUhi8DokqOsxj8aEISD5EMFc5AxKMoOgTtm7tuZV/0DStc=
    repository: https://upload.pypi.org/legacy
    skip_cleanup: true
    on:
      python: '2.7'
