language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - cp .env.example .env
install:
  - pip install tox-travis
  - pip install bumpversion
  - pip install -r requirements.txt
# command to run tests
script:
  - pip install -U python-dotenv
  - tox
